#######################################################################################
# Book settings
title : Tecnologie & Software di Data Science 
author: Manuel Rucci / Daniele Grotti
logo: 'logo.png'

# Information about where the book exists on the web
description: >-
  Libro di Machine Learning e Data Visualization

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "off"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : true

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/visiont3lab/tecnologie_data_science
  path_to_book                : "book"
  branch                      : master

latex:
  latex_engine                : "xelatex"